### ISSUE TITLE
Can it work on PyQt5?

### ISSUE THREAD

**Issue by castieldc** [GvozdevLeonid/BackDrop-in-PyQt-PySide#1]
I tried in PyQt5 in Python 3.7, got output: "interrupted by signal 11: SIGSEGV", seems not working. Then I change to PySide6 in Python 3.10, it works fine. So PyQt5 is not supported? How about PyQt6?

**Comment by GvozdevLeonid** [comment]
I will add support for pyqt in the coming days. also only python 3.10 version is available so far.

**Comment by castieldc** [comment]
Also, shine_animation is not working, it keeps printing NameError when i hover:

Traceback (most recent call last):
  File "<frozen Glassmorphism>", line 296, in event
  File "<frozen Glassmorphism>", line 211, in _shine_animation
  File "<frozen Glassmorphism>", line 126, in _create_animation_pixmap
NameError: name 'math' is not defined
Traceback (most recent call last):
  File "<frozen Glassmorphism>", line 305, in event
  File "<frozen Glassmorphism>", line 211, in _shine_animation
  File "<frozen Glassmorphism>", line 126, in _create_animation_pixmap
NameError: name 'math' is not defined

I don't need this feature, so i just remove the code.

**Comment by GvozdevLeonid** [comment]
Thanks

**Comment by castieldc** [comment]
> I will add support for pyqt in the coming days. also only python 3.10 version is available so far.
Ok, I'll try python 3.10
